version: "3"
services:
  backend:
    container_name: backend
    build: ./backend/
    depends_on:
      - db
    environment:
      DATABASE_URL: postgres://user:password@db/db
      NODE_ENV: development
      PORT: 4000
    expose:
      - 4000
    ports:
      - "4000:4000"
    volumes:
      - ./backend:/usr/app
      - /usr/app/node_modules

  db:
    container_name: db
    image: postgres
    expose:
      - 5432
    environment:
      POSTGRES_PASSWORD: password
      POSTGRES_USER: user
      POSTGRES_DB: db
    volumes: 
      - ./backend/src/migrations/dbinit.sql:/docker-entrypoint-initdb.d/init.sql
    logging:
      driver: none

  frontend:
    container_name: frontend
    build: ./frontend/
    command: npm start
    volumes:
      - ./frontend:/usr/app
      - /usr/app/node_modules
    depends_on:
      - backend
    ports:
      - "3000:3000"
    logging:
      driver: none
    links:
      - backend

volumes:
    db-data:
    pgadmin-data:
